apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-vite-react
  labels:
    app: example-vite-react
spec:
  selector:
    matchLabels:
      app: example-vite-react
  template:
    metadata:
      labels:
        app: example-vite-react
    spec:
      containers:
        - name: example-vite-react
          image: example-vite-react-image
          env:
            - name: BACKEND_URL
              value: 'http://example-go-api/api'
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: example-vite-react
spec:
  selector:
    app: example-vite-react
  ports:
    - name: example-vite-react
      port: 5173
      targetPort: 5173
      protocol: TCP
